--***
--***  SQL Server CE version.
--***
SELECT C.CONSTRAINT_NAME
     , C.REFERENCED_TABLE_NAME
     , C.REFERENCED_COLUMN_NAME
     , C.TABLE_NAME
     , C.CONSTRAINT_COLUMN_NAME
  FROM MSysConstraints C
  WHERE C.CONSTRAINT_TYPE = 1


--***
--***  SQL Server version.
--***
SELECT C.CONSTRAINT_NAME
     , PK.TABLE_NAME
     , PK.COLUMN_NAME
     , FK.TABLE_NAME
     , FK.COLUMN_NAME
  FROM Information_Schema.REFERENTIAL_CONSTRAINTS C
  JOIN Information_Schema.CONSTRAINT_COLUMN_USAGE PK 
    ON PK.CONSTRAINT_NAME = C.UNIQUE_CONSTRAINT_NAME
  JOIN Information_Schema.CONSTRAINT_COLUMN_USAGE FK 
    ON FK.CONSTRAINT_NAME = C.CONSTRAINT_NAME

