// Rapi.cs - P/Invoke wrappers for RAPI functions
//
// Generated by PInvoke Wizard (v 1.0) from The Paul Yao Company http://www.paulyao.com 
//
// Code from _Programming the .NET Compact Framework with C#_
// and _Programming the .NET Compact Framework with VB_
// (c) Copyright 2002-2004 Paul Yao and David Durant. 
// All rights reserved.

using System;
using System.Runtime.InteropServices;

namespace YaoDurant.Win32
{
   /// <summary>
   /// Rapi - Wrapper for ActiveSync RAPI functions.
   /// </summary>
   public struct Rapi
   {
      public const string DllName = "rapi.dll";
      public const int MAX_PATH = 260;
      public const int S_OK = 0;
      public const int ERROR_SUCCESS = 0;
      public const int ERROR_NO_MORE_ITEMS = 259;
      public const int E_FAIL = unchecked((int)0x80004005);
      public const int RAPI_TRUE = 1;
      public const int RAPI_FALSE = 0;
      public static IntPtr INVALID_HANDLE_VALUE  = 
         new IntPtr(unchecked((int)0xffffffff));

      // Registry values.
      public static IntPtr HKEY_CLASSES_ROOT  = 
         new IntPtr(unchecked((int)0x80000000));
      public static IntPtr HKEY_CURRENT_USER  = 
         new IntPtr(unchecked((int)0x80000001));
      public static IntPtr HKEY_LOCAL_MACHINE = 
         new IntPtr(unchecked((int)0x80000002));
      public static IntPtr HKEY_USERS         = 
         new IntPtr(unchecked((int)0x80000003));

      [StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode,Pack=4)]
         public struct CE_FIND_DATA
      {
         public int dwFileAttributes;
         public FILETIME ftCreationTime;
         public FILETIME ftLastAccessTime;
         public FILETIME ftLastWriteTime;
         public int nFileSizeHigh;
         public int nFileSizeLow;
         public int dwOID;
         [ MarshalAs( UnmanagedType.ByValTStr, SizeConst=MAX_PATH)]
         public string cFileName;
      };

      [StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode,Pack=4)]
      public struct CEPROPID
      {
         CEVT type;
         short id;
      }

      public enum FAF
      {
         FAF_ATTRIBUTES = 0x01,
         FAF_CREATION_TIME = 0x02,
         FAF_LASTACCESS_TIME = 0x04,
         FAF_LASTWRITE_TIME = 0x08,
         FAF_SIZE_HIGH = 0x10,
         FAF_SIZE_LOW = 0x20,
         FAF_OID = 0x40,
         FAF_NAME = 0x80,
         FAF_FLAG_COUNT = 8,
         FAF_ATTRIB_CHILDREN = 0x01000,
         FAF_ATTRIB_NO_HIDDEN = 0x02000,
         FAF_FOLDERS_ONLY = 0x04000,
         FAF_NO_HIDDEN_SYS_ROMMODULES = 0x08000,
         FAF_GETTARGET = 0x10000,
      }

      public enum FAD
      {
         FAD_OID = 0x01,
         FAD_FLAGS = 0x02,
         FAD_NAME = 0x04,
         FAD_TYPE = 0x08,
         FAD_NUM_RECORDS = 0x10,
         FAD_NUM_SORT_ORDER = 0x20,
         FAD_SIZE = 0x40,
         FAD_LAST_MODIFIED = 0x80,
         FAD_SORT_SPECS = 0x100,
         FAD_FLAG_COUNT = 9,
      }

      public enum FILE_ATTRIBUTE
      {
         FILE_ATTRIBUTE_HAS_CHILDREN = 0x00010000,
         FILE_ATTRIBUTE_SHORTCUT = 0x00020000,
         FILE_ATTRIBUTE_READONLY = 0x00000001,
         FILE_ATTRIBUTE_HIDDEN = 0x00000002,
         FILE_ATTRIBUTE_SYSTEM = 0x00000004,
         FILE_ATTRIBUTE_DIRECTORY = 0x00000010,
         FILE_ATTRIBUTE_ARCHIVE = 0x00000020,
         FILE_ATTRIBUTE_INROM = 0x00000040,
         FILE_ATTRIBUTE_ENCRYPTED = 0x00000040,
         FILE_ATTRIBUTE_NORMAL = 0x00000080,
         FILE_ATTRIBUTE_TEMPORARY = 0x00000100,
         FILE_ATTRIBUTE_SPARSE_FILE = 0x00000200,
         FILE_ATTRIBUTE_REPARSE_POINT = 0x00000400,
         FILE_ATTRIBUTE_COMPRESSED = 0x00000800,
         FILE_ATTRIBUTE_OFFLINE = 0x00001000,
         FILE_ATTRIBUTE_ROMSTATICREF = 0x00001000,
         FILE_ATTRIBUTE_NOT_CONTENT_INDEXED = 0x00002000,
         FILE_ATTRIBUTE_ROMMODULE = 0x00002000,
      }

      public enum RAPI_ERROR
      {
         ERROR_FILE_NOT_FOUND = 2,
         ERROR_PATH_NOT_FOUND = 3,
         ERROR_TOO_MANY_OPEN_FILES = 4,
         ERROR_ACCESS_DENIED = 5,
         ERROR_INVALID_HANDLE = 6,
      }

      public enum RAPISTREAMFLAG
      {
         STREAM_TIMEOUT_READ,
      };

      public enum REGTYPE
      {
         REG_NONE = 0,
         REG_SZ = 1,
         REG_EXPAND_SZ = 2,
         REG_BINARY = 3,
         REG_DWORD = 4,
         REG_DWORD_LITTLE_ENDIAN = 4,
         REG_DWORD_BIG_ENDIAN = 5,
         REG_LINK = 6,
         REG_MULTI_SZ = 7,
         REG_RESOURCE_LIST = 8
      }

      public interface ISequentialStream
      {
         int Read(ref byte pv, int cb, ref int pcbRead);
         int Write(ref byte pv,int cb, ref int pcbWritten);
      }

      public interface IStream : ISequentialStream
      {
      int Seek(long dlibMove, int dwOrigin, ref ulong plibNewPosition);
      int SetSize(ulong libNewSize);
      int CopyTo(IStream pstm, ulong cb, ref ulong pcbRead, ref ulong pcbWritten);
      int Commit(int grfCommitFlags);
      int Revert();
      int LockRegion(ulong libOffset, ulong cb, int dwLockType);
      int UnlockRegion(ulong libOffset, ulong cb, int dwLockType);
      int Stat(ref STATSTG pstatstg, int grfStatFlag);
      int Clone(ref IStream ppstm);
      }

      public interface IRAPIStream : IStream
      {
         int SetRapiStat(int dwValue);
         int GetRapiStat(ref int pdwValue);
      };

      [StructLayout(LayoutKind.Sequential,Pack=4)]
         public struct STORE_INFORMATION
      {
         int dwStoreSize;
         int dwFreeSize;
      };

      [StructLayout(LayoutKind.Sequential,Pack=4)]
         public struct CEGUID
      {
         int Data1;
         int Data2;
         int Data3;
         int Data4;
      };

      [StructLayout(LayoutKind.Sequential,Pack=4)]
         public struct CENOTIFICATION
      {
         int dwSize;
         int dwParam;
         int uType;
         CEGUID guid;
         int oid;
         int oidParent;
      };

      public const int CEDB_EXNOTIFICATION = 0x00000001;

      [StructLayout(LayoutKind.Sequential,Pack=4)]
         public struct CENOTIFYREQUEST
      {
         int dwSize;
         IntPtr hwnd;
         int dwFlags;
         IntPtr hHeap;
         int dwParam;
      };

      [StructLayout(LayoutKind.Sequential,Pack=4,CharSet=CharSet.Unicode)]
         public struct CEFILEINFO
      {
         int dwAttributes;
         int oidParent;
         [ MarshalAs( UnmanagedType.ByValTStr, SizeConst=MAX_PATH)]
         string szFileName;
         FILETIME ftLastChanged;
         int dwLength;
      };

     [StructLayout(LayoutKind.Sequential,Pack=4,CharSet=CharSet.Unicode)]
         public struct CEDIRINFO
      {
         int dwAttributes;
         int oidParent;
         [ MarshalAs( UnmanagedType.ByValTStr, SizeConst=MAX_PATH)]
         string szDirName;
      };

      [StructLayout(LayoutKind.Sequential,Pack=4)]
         public struct CERECORDINFO
      {
         int oidParent;
      };

       public enum CEDB_SORT
      {
         CEDB_SORT_DESCENDING = 0x00000001,
         CEDB_SORT_CASEINSENSITIVE = 0x00000002,
         CEDB_SORT_UNKNOWNFIRST = 0x00000004,
         CEDB_SORT_GENERICORDER = 0x00000008,
      }

      [StructLayout(LayoutKind.Sequential,Pack=4)]
         public struct SORTORDERSPEC
      {
         public int propid;
         public int dwFlags;
      };


      public const int CEDB_MAXDBASENAMELEN = 32;
      public const int CEDB_MAXSORTORDER = 4;

      public enum CEDB
      {
         CEDB_VALIDNAME = 0x0001,
         CEDB_VALIDTYPE = 0x0002,
         CEDB_VALIDSORTSPEC = 0x0004,
         CEDB_VALIDMODTIME = 0x0008,
         CEDB_VALIDDBFLAGS = 0x0010,
         CEDB_VALIDCREATE = CEDB_VALIDNAME|CEDB_VALIDTYPE|CEDB_VALIDSORTSPEC|CEDB_VALIDDBFLAGS,
         CEDB_NOCOMPRESS = 0x00010000,
      }

      [StructLayout(LayoutKind.Sequential,Pack=4,CharSet=CharSet.Unicode)]
      public struct CEDBASEINFO
      {
         public int dwFlags;
         [ MarshalAs( UnmanagedType.ByValTStr, SizeConst=CEDB_MAXDBASENAMELEN)]
         public string szDbaseName;
         public int dwDbaseType;
         public short wNumRecords;
         public short wNumSortOrder;
         public int dwSize;
         public FILETIME ftLastModified;

         // public SORTORDERSPEC [] rgSortSpecs;
         // Try #2 -- This works.
         public SORTORDERSPEC rgSortSpec1;
         public SORTORDERSPEC rgSortSpec2;
         public SORTORDERSPEC rgSortSpec3;
         public SORTORDERSPEC rgSortSpec4;

#if false
         // public SORTORDERSPEC [] rgSortSpecs;
         // Try #3: This works also - but not as nice.
         public int Sort1_propid;
         public int Sort1_dwFlags;
         public int Sort2_propid;
         public int Sort2_dwFlags;
         public int Sort3_propid;
         public int Sort3_dwFlags;
         public int Sort4_propid;
         public int Sort4_dwFlags;

         // public SORTORDERSPEC [] rgSortSpecs;
         // Try #1: The original - DESKTOP P/Invoke cannot deal with this
         // Desktop P/Invoke cannot deal with this - 
         // problem with structure array in a structure in a structure?!?
         [ MarshalAs( UnmanagedType.ByValArray, SizeConst=CEDB_MAXSORTORDER)]
         public SORTORDERSPEC [] rgSortSpecs;
#endif
      };

      [StructLayout(LayoutKind.Sequential,Pack=4,CharSet=CharSet.Unicode)]
         public struct CEDB_FIND_DATA
      {
         public int OidDb;
         public CEDBASEINFO DbInfo;
      };

      public enum OBJTYPE
      {
         OBJTYPE_INVALID = 0,
         OBJTYPE_FILE = 1,
         OBJTYPE_DIRECTORY = 2,
         OBJTYPE_DATABASE = 3,
         OBJTYPE_RECORD = 4,
      }

      [StructLayout(LayoutKind.Sequential,Pack=4,CharSet=CharSet.Unicode)]
         public struct CEOIDINFO
      {
         short wObjType;
         short wPad;
         [StructLayout(LayoutKind.Explicit)]
            public struct _NESTED_CEOIDINFO_UNION
            {
               [FieldOffset(0)] CEFILEINFO infFile;
               [FieldOffset(0)] CEDIRINFO infDirectory;
               [FieldOffset(0)] CEDBASEINFO infDatabase;
               [FieldOffset(0)] CERECORDINFO infRecord;
            };
      };

      public const int CEDB_AUTOINCREMENT = 0x00000001;

      public enum CEDB_SEEK
      {
         CEDB_SEEK_CEOID = 0x00000001,
         CEDB_SEEK_BEGINNING = 0x00000002,
         CEDB_SEEK_END = 0x00000004,
         CEDB_SEEK_CURRENT = 0x00000008,
         CEDB_SEEK_VALUESMALLER = 0x00000010,
         CEDB_SEEK_VALUEFIRSTEQUAL = 0x00000020,
         CEDB_SEEK_VALUEGREATER = 0x00000040,
         CEDB_SEEK_VALUENEXTEQUAL = 0x00000080,
      }
      
      [StructLayout(LayoutKind.Sequential,Pack=4)]
         public struct CEBLOB
      {
         int dwCount;
         Byte [] lpb;
      };

      public enum CEVT : short
      {
         CEVT_I2 = 2,
         CEVT_UI2 = 18,
         CEVT_I4 = 3,
         CEVT_UI4 = 19,
         CEVT_FILETIME = 64,
         CEVT_LPWSTR = 31,
         CEVT_BLOB = 65,
         CEVT_BOOL = 11,
         CEVT_R8 = 5,
      }

      [StructLayout(LayoutKind.Explicit,CharSet=CharSet.Unicode)]
         public struct CEVALUNION
      {
         [FieldOffset(0)] short iVal;
         [FieldOffset(0)] ushort uiVal;
         [FieldOffset(0)] int lVal;
         [FieldOffset(0)] uint ulVal;
         [FieldOffset(0)] FILETIME filetime;
         [FieldOffset(0)] string lpwstr;
         [FieldOffset(0)] CEBLOB blob;
         [FieldOffset(0)] int boolVal;
         [FieldOffset(0)] Double dblVal;
      };

      public enum CEDB_PROPVAL_FLAGS
      {
         CEDB_PROPNOTFOUND = 0x0100,
         CEDB_PROPDELETE = 0x0200,
      }

      [StructLayout(LayoutKind.Sequential,Pack=4,CharSet=CharSet.Unicode)]
         public struct CEPROPVAL
      {
         int propid;
         short wLenData;
         short wFlags;
         CEVALUNION val;
      };

      public const int CEDB_MAXDATABLOCKSIZE = 4092;
      public const int CEDB_MAXPROPDATASIZE = CEDB_MAXDATABLOCKSIZE*16;
      public const int CEDB_MAXRECORDSIZE = 128*1024;
      
      public enum CEDB_READRECORDPROPFLAGS
      {
         CEDB_ALLOWREALLOC = 0x00000001,
      }

       public enum SYSMEM
      {
         SYSMEM_CHANGED = 0,
         SYSMEM_MUSTREBOOT = 1,
         SYSMEM_REBOOTPENDING = 2,
         SYSMEM_FAILED = 3,
      }

       [StructLayout(LayoutKind.Sequential,Pack=4,CharSet=CharSet.Unicode)]
         public struct CEOSVERSIONINFO
      {
         int dwOSVersionInfoSize;
         int dwMajorVersion;
         int dwMinorVersion;
         int dwBuildNumber;
         int dwPlatformId;
         [ MarshalAs( UnmanagedType.ByValTStr, SizeConst=128)]
         string szCSDVersion;
      };

      public enum AC
      {
         AC_LINE_OFFLINE = 0x00,
         AC_LINE_ONLINE = 0x01,
         AC_LINE_BACKUP_POWER = 0x02,
         AC_LINE_UNKNOWN = 0xFF,
      }

      public enum BATTERY_FLAG
      {
         BATTERY_FLAG_HIGH = 0x01,
         BATTERY_FLAG_LOW = 0x02,
         BATTERY_FLAG_CRITICAL = 0x04,
         BATTERY_FLAG_CHARGING = 0x08,
         BATTERY_FLAG_NO_BATTERY = 0x80,
         BATTERY_FLAG_UNKNOWN = 0xFF,
      }

      public const int BATTERY_PERCENTAGE_UNKNOWN = 0xFF;
      public const int BATTERY_LIFE_UNKNOWN = unchecked((int)0xFFFFFFFF);

      public enum REGDISP
      {
         REG_CREATED_NEW_KEY = 0x00000001,
         REG_OPENED_EXISTING_KEY = 0x00000002,
      }

      [StructLayout(LayoutKind.Sequential,Pack=4)]
         public struct SYSTEM_POWER_STATUS_EX
      {
         Byte ACLineStatus;
         Byte BatteryFlag;
         Byte BatteryLifePercent;
         Byte Reserved1;
         int BatteryLifeTime;
         int BatteryFullLifeTime;
         Byte Reserved2;
         Byte BackupBatteryFlag;
         Byte BackupBatteryLifePercent;
         Byte Reserved3;
         int BackupBatteryLifeTime;
         int BackupBatteryFullLifeTime;
      };

      public const int CERAPI_E_ALREADYINITIALIZED = unchecked((int)0x80041001);

      [StructLayout(LayoutKind.Sequential,Pack=4)]
      public struct RAPIINIT
      {
         public int cbSize;
         public IntPtr heRapiInit;
         public int hrRapiInit;
      };

      [StructLayout(LayoutKind.Sequential,Pack=4)]
      public struct SYSTEM_INFO
      {
         [StructLayout(LayoutKind.Explicit)]
         public struct _SYSTEM_INFO_ARCH
         {
            [FieldOffset(0)] int dwOemId;
            [FieldOffset(0)] short wProcessorArchitecture;
            [FieldOffset(2)] short wReserved;
         };
         int dwPageSize;
         Byte [] lpMinimumApplicationAddress;
         Byte [] lpMaximumApplicationAddress;
         int dwActiveProcessorMask;
         int dwNumberOfProcessors;
         int dwProcessorType;
         int dwAllocationGranularity;
         short wProcessorLevel;
         short wProcessorRevision;
      };

      [StructLayout(LayoutKind.Sequential,Pack=4)]
         public struct PROCESS_INFORMATION
      {
         public IntPtr hProcess;
         public IntPtr hThread;
         public int dwProcessId;
         public int dwThreadId;
      };

      [StructLayout(LayoutKind.Sequential,Pack=4)]
         public struct MEMORYSTATUS
      {
         int dwLength;
         int dwMemoryLoad;
         int dwTotalPhys;
         int dwAvailPhys;
         int dwTotalPageFile;
         int dwAvailPageFile;
         int dwTotalVirtual;
         int dwAvailVirtual;
      };

      // From WINBASE.H -- for CeCreateFile
      public enum ACCESS : uint
      {
         READ = 0x80000000,
         WRITE = 0x40000000,
      }
      // From WINBASE.H -- for CeCreateFile
      public enum SHARE
      {
         READ = 0x00000001,
         WRITE = 0x00000002,
      }
      // From WINBASE.H -- for CeCreateFile
      public enum ACTION
      {
         CREATE_NEW = 1,
         CREATE_ALWAYS = 2,
         OPEN_EXISTING = 3,
         OPEN_ALWAYS = 4,
         TRUNCATE_EXISTING = 5
      }
      // From WINBASE.H -- for CeCreateFile
      public enum FILEFLAGATT : uint
      {
         ATTRIBUTE_READONLY = 0x00000001,
         ATTRIBUTE_HIDDEN = 0x00000002,
         ATTRIBUTE_SYSTEM = 0x00000004,
         ATTRIBUTE_DIRECTORY = 0x00000010,
         ATTRIBUTE_ARCHIVE = 0x00000020,
         ATTRIBUTE_INROM = 0x00000040,
         ATTRIBUTE_ENCRYPTED = 0x00000040,
         ATTRIBUTE_NORMAL = 0x00000080,
         ATTRIBUTE_TEMPORARY = 0x00000100,
         ATTRIBUTE_SPARSE_FILE = 0x00000200,
         ATTRIBUTE_REPARSE_POINT = 0x00000400,
         ATTRIBUTE_COMPRESSED = 0x00000800,
         ATTRIBUTE_OFFLINE = 0x00001000,
         ATTRIBUTE_ROMSTATICREF = 0x00001000,
         ATTRIBUTE_NOT_CONTENT_INDEXED = 0x00002000,
         ATTRIBUTE_ROMMODULE = 0x00002000,
         FLAG_WRITE_THROUGH = 0x80000000,
         FLAG_OVERLAPPED = 0x40000000,
         FLAG_NO_BUFFERING = 0x20000000,
         FLAG_RANDOM_ACCESS = 0x10000000,
         FLAG_SEQUENTIAL_SCAN = 0x08000000,
         FLAG_DELETE_ON_CLOSE = 0x04000000,
         FLAG_BACKUP_SEMANTICS = 0x02000000,
         FLAG_POSIX_SEMANTICS = 0x01000000,
      }

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeCheckPassword (string lpszPassword);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeCloseHandle (IntPtr hObject);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeCopyFile (string lpExistingFileName, string lpNewFileName, int bFailIfExists);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeCreateDatabase (string lpszName, int dwDbaseType, short wNumSortOrder, ref SORTORDERSPEC rgSortSpecs);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeCreateDatabaseEx (ref System.Guid pceguid, ref CEDBASEINFO lpCEDBInfo);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeCreateDirectory (string lpPathName, int Reserved);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern IntPtr CeCreateFile (string lpFileName, ACCESS dwDesiredAccess, SHARE dwShareMode, int Res1, ACTION dwCreationDisposition, FILEFLAGATT dwFlagsAndAttributes, int Res2);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeCreateProcess (string lpApplicationName, string lpCommandLine, int Res1, int Res2, int Res3, int dwCreationFlags, int Res4, int Res5, int Res6, ref PROCESS_INFORMATION lpProcessInformation);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeCreateProcess (string lpApplicationName, int Zero, int Res1, int Res2, int Res3, int dwCreationFlags, int Res4, int Res5, int Res6, ref PROCESS_INFORMATION lpProcessInformation);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeDeleteDatabase (int oidDbase);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeDeleteDatabaseEx (ref System.Guid  pguid, int oid);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeDeleteFile (string lpFileName);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeDeleteRecord (IntPtr hDatabase, int oidRecord);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeEnumDBVolumes (ref System.Guid  pceguid, string lpBuf, int dwNumChars);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeFindAllDatabases (int dwDbaseType, FAD wFlags, ref short cFindData, ref IntPtr ppFindData);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeFindAllFiles (string szPath, FAF dwFlags, ref int lpdwFoundCount, ref IntPtr ppFindDataArray);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeFindClose (IntPtr hFindFile);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern IntPtr CeFindFirstDatabase (int dwDbaseType);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern IntPtr CeFindFirstDatabaseEx (ref System.Guid  pceguid, int dwDbaseType);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern IntPtr CeFindFirstFile (string lpFileName, ref CE_FIND_DATA lpFindFileData);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeFindNextDatabase (IntPtr hEnum);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeFindNextDatabaseEx (IntPtr hEnum, ref System.Guid  pceguid);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeFindNextFile (IntPtr hFindFile, ref CE_FIND_DATA lpFindFileData);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeGetClassName (IntPtr hWnd, string lpClassName, int nMaxCount);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeGetDesktopDeviceCaps (int nIndex);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeGetFileAttributes (string lpFileName);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeGetFileSize (IntPtr hFile, ref int lpFileSizeHigh);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeGetFileTime (IntPtr hFile, ref FILETIME lpCreationTime, ref FILETIME lpLastAccessTime, ref FILETIME lpLastWriteTime);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeGetLastError ();

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeGetSpecialFolderPath (int nFolder, int nBufferLength, string lpBuffer);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeGetStoreInformation (ref STORE_INFORMATION lpsi);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern void CeGetSystemInfo (ref SYSTEM_INFO lpSystemInfo);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeGetSystemPowerStatusEx (ref SYSTEM_POWER_STATUS_EX pstatus, int fUpdate);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeGetTempPath (int nBufferLength, string lpBuffer);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeGetVersionEx (ref CEOSVERSIONINFO lpVersionInformation);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern IntPtr CeGetWindow (IntPtr hWnd, int uCmd);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeGetWindowLong (IntPtr hWnd, int nIndex);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeGetWindowText (IntPtr hWnd, string lpString, int nMaxCount);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern void CeGlobalMemoryStatus (ref MEMORYSTATUS lpmst);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeMountDBVol (ref System.Guid  pceguid, string lpszDBVol, int dwFlags);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeMoveFile (string lpExistingFileName, string lpNewFileName);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeOidGetInfo (int oid, ref CEOIDINFO poidInfo);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeOidGetInfoEx (ref System.Guid  pceguid, int oid, ref CEOIDINFO poidInfo);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern IntPtr CeOpenDatabase (ref int poid, string lpszName, int propid, int dwFlags, IntPtr hwndNotify);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern IntPtr CeOpenDatabaseEx (ref System.Guid  pceguid, ref int poid, string lpszName, int propid, int dwFlags, ref CENOTIFYREQUEST pRequest);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeRapiFreeBuffer (IntPtr pBuffer);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeRapiGetError ();

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeRapiInit ();

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeRapiInitEx (ref RAPIINIT pRapiInit);

      // Block mode – Set ppIRAPIStream to zero
      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeRapiInvoke (string pDllPath, string pFunctionName, int cbInput, IntPtr pInput,   ref int pcbOutput, ref IntPtr ppOutput, int Res1, int Res2);

      // Stream interface mode – Set ppIRAPIStream to valid IRAPIStream interface
      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeRapiInvoke (string pDllPath, string pFunctionName, int cbInput, IntPtr pInput, int Res1, int Res2, ref IRAPIStream ppIRAPIStream, int dwReserved);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeRapiUninit ();

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeReadFile (IntPtr hFile, IntPtr lpBuffer, int nNumberOfBytesToRead, ref int lpNumberOfBytesRead, int Reserved);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeReadRecordProps (IntPtr hDbase, int dwFlags, ref short lpcPropID, ref CEPROPID rgPropID, ref IntPtr lplpBuffer, ref int lpcbBuffer);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeReadRecordPropsEx (IntPtr hDbase, int dwFlags, ref short lpcPropID, ref CEPROPID rgPropID, ref IntPtr lplpBuffer, ref int lpcbBuffer, IntPtr hHeap);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeRegCloseKey (IntPtr hKey);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeRegCreateKeyEx (IntPtr hKey, string lpszSubKey, int Reserved, int Reserved2, int Reserved3, int Reserved4, int Reserved5, ref IntPtr phkResult, ref REGDISP lpdwDisposition);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeRegDeleteKey (IntPtr hKey, string lpszSubKey);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeRegDeleteValue (IntPtr hKey, string lpszValueName);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeRegEnumKeyEx (IntPtr hKey, int dwIndex, string lpName, ref int lpcbName, int Reserved, string lpClass, ref int lpcbClass, int Reserved2);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeRegEnumKeyEx (IntPtr hKey, int dwIndex, string lpName, ref int lpcbName, int Res1, int Res2, int Res3, int Res4);

      [DllImport("rapi.dll", CharSet=CharSet.Unicode)]
      public static extern int CeRegEnumValue (IntPtr hKey, int dwIndex, string lpszName, ref int lpcbName, int Res, ref REGTYPE lpType, IntPtr lpData, ref int lpcbData);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeRegOpenKeyEx (IntPtr hKey, string lpszSubKey, int Reserved1, int Reserved2, ref IntPtr phkResult);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeRegQueryInfoKey (IntPtr hKey, string lpClass, ref int lpcbClass, int Res1, ref int lpcSubKeys, ref int lpcbMaxSubKeyLen, ref int lpcbMaxClassLen, ref int lpcValues, ref int lpcbMaxValueNameLen, ref int lpcbMaxValueLen, int Res2, ref FILETIME lpftLastWriteTime);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeRegQueryValueEx (IntPtr hKey, string lpValueName, int Res1, ref REGTYPE lpType, IntPtr iptrData, ref int lpcbData);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeRegQueryValueEx (IntPtr hKey, string lpValueName, int Res1, ref REGTYPE lpType, string strData, ref int lpcbData);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeRegQueryValueEx (IntPtr hKey, string lpValueName, int lpReserved, ref REGTYPE lpType, ref int piData, ref int lpcbData);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeRegSetValueEx (IntPtr hKey, string lpValueName, int Reserved, REGTYPE dwType, IntPtr lpData, int cbData);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeRegSetValueEx (IntPtr hKey, string lpValueName, int Reserved, REGTYPE dwType, string lpData, int cbData);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeRegSetValueEx (IntPtr hKey, string lpValueName, int Reserved, REGTYPE dwType, ref int lpData, int cbData);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeRemoveDirectory (string lpPathName);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeSeekDatabase (IntPtr hDatabase, int dwSeekType, int dwValue, ref int lpdwIndex);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeSetDatabaseInfo (int oidDbase, ref CEDBASEINFO pNewInfo);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeSetDatabaseInfoEx (ref System.Guid  pceguid, int oidDbase, ref CEDBASEINFO pNewInfo);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeSetEndOfFile (IntPtr hFile);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeSetFileAttributes (string lpFileName, int dwFileAttributes);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeSetFilePointer (IntPtr hFile, int lDistanceToMove, ref int lpDistanceToMoveHigh, int dwMoveMethod);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeSetFileTime (IntPtr hFile, ref FILETIME lpCreationTime, ref FILETIME lpLastAccessTime, ref FILETIME lpLastWriteTime);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeSHCreateShortcut (string lpszShortcut, string lpszTarget);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeSHGetShortcutTarget (string lpszShortcut, string lpszTarget, int cbMax);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeUnmountDBVol (ref System.Guid  pceguid);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeWriteFile (IntPtr hFile, IntPtr lpBuffer, int nNumberOfBytesToWrite, ref int lpNumberOfBytesWritten, int Reserved);

      [DllImport(DllName, CharSet=CharSet.Unicode)]
      public static extern int CeWriteRecordProps (IntPtr hDbase, int oidRecord, short cPropID, ref CEPROPVAL rgPropVal);

   } // class Rapi
} // namespace YaoDurant.Win32
